//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSMTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSMTracker.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 OSM轨迹记录仪 的本地化字符串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string BtnCheck {
            get {
                return ResourceManager.GetString("BtnCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绘制 的本地化字符串。
        /// </summary>
        public static string BtnDraw {
            get {
                return ResourceManager.GetString("BtnDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录制 的本地化字符串。
        /// </summary>
        public static string BtnRecord {
            get {
                return ResourceManager.GetString("BtnRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分享 的本地化字符串。
        /// </summary>
        public static string BtnShare {
            get {
                return ResourceManager.GetString("BtnShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string BtnSort {
            get {
                return ResourceManager.GetString("BtnSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string BtnStop {
            get {
                return ResourceManager.GetString("BtnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传 的本地化字符串。
        /// </summary>
        public static string BtnUpload {
            get {
                return ResourceManager.GetString("BtnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现位置： 的本地化字符串。
        /// </summary>
        public static string CurrentStatic {
            get {
                return ResourceManager.GetString("CurrentStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨迹 的本地化字符串。
        /// </summary>
        public static string ManagePageTitle {
            get {
                return ResourceManager.GetString("ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string MIAbout {
            get {
                return ResourceManager.GetString("MIAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用设置 的本地化字符串。
        /// </summary>
        public static string MIAppSetting {
            get {
                return ResourceManager.GetString("MIAppSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录制设置 的本地化字符串。
        /// </summary>
        public static string MIRecordSetting {
            get {
                return ResourceManager.GetString("MIRecordSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftToRight 的本地化字符串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-Hans 的本地化字符串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 追踪 的本地化字符串。
        /// </summary>
        public static string TrackingPageTitle {
            get {
                return ResourceManager.GetString("TrackingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置信息暂时未知。 的本地化字符串。
        /// </summary>
        public static string UnknownLocation {
            get {
                return ResourceManager.GetString("UnknownLocation", resourceCulture);
            }
        }
    }
}
